### PR TITLE
Addition to "Some helpful terminology"

### PR DESCRIPTION
**Pull request by PaulApivat**
**Common knowledge** is a special kind of (shared) knowledge among a group of people that allow them to act as if a piece of knowledge were fact [3][4]. It is colloquially represented by the phrase, “I know that you know. And I know that you know that I know.” In the context of governance, it allows people to enforce norms (i.e., voting norms, decision-making norms, norms around debate and discussion). [3]

[3] https://en.wikipedia.org/wiki/Common_knowledge_(logic)
[4] Vlad Zamfir presentation “Blockchain Governance 101” at Beyond Block Taipei (2017) https://www.youtube.com/watch?v=9RtSod8EXn4&feature=youtu.be&t=2h40m05s

### CODE REVIEW

**Comment by PaulApivat** [comment]
@lrettig thank you for breakdown - finger crossed this works! (otherwise, I'll be at Edcon; we could probably get this working in a few minutes :)

**Comment by PaulApivat** [comment]
hi @lrettig when i want to add additional separate, contributions, do i need to close out this PR (#3) first?

**Comment by lrettig** [comment]
Hey @PaulApivat sorry for the slow response time and sorry we failed to connect at EdCon! Appreciate the contribution. Andreas said today is the deadline for new content so I'm making a push to finish the first draft of this chapter today.

**Comment by PaulApivat** [comment]
Sounds good @lrettig. Happy to add more content with a second draft - I guess I could do another PR when you're ready for additional content. 

If it's not too late to make the deadline, here's another paragraph to add:

//// TODO: mention solutions, Nash equilibria ////

In Game Theory, a Nash Equilibrium is a solution when players know the strategies of other players, and have a **dominant strategy**, where they do wouldn’t change their strategy, regardless of what the other player does. Neither player stands to gain from changing their strategies.

The aforementioned Prisoner’s Dilemma has a Nash Equilibrium where each player has a dominant strategy to betray. However, a dominant strategy doesn’t necessarily lead to better outcomes. 

Having a way for players to communicate may lead them **away** from their dominant strategy, but achieve better outcomes. One role of governance is, in part, to facilitate communication and coordination such that people may achieve better joint outcomes even when that means deviating from their individual dominant strategies.

**Pull request closed without merging**
